name: HungerGames
main: tk.shanebee.hg.AG
authors: [bob7l, Spoopy, ShaneBee]
description: A Simple, fun, PvP arena plugin
version: '${project.version}'
website: https://bitbucket.org/ShaneBeeStudios/hungergames
api-version: '1.13'
softdepend: [Multiverse-Core, MultiWorld, Vault, My_Worlds, GoldenEnchants, mcMMO, MythicMobs]

commands:
  hg:
    description: HungerGames Base command