blank_issues_enabled: false
contact_links:
  - name: 💻 ShaneBee's Support Discord
    url: https://discord.gg/UzBCFSQJyM
    about: For general help with HungerGames ask in the HungerGames channel
  - name: 🛠️Modrinth Resource
    url: https://modrinth.com/plugin/hungergames-sb
    about: Read about and download HungerGames on Modrinth!
