name: 👷 Feature Request
description: Request an addition or change to HungerGames
labels: "needs triage"
type: "Feature"
body:
    - type: textarea
      id: suggestion
      attributes:
          label: Suggestion
          description: What would you like to see improved?
          placeholder: |
              The more details, the better
      validations:
          required: true

    - type: textarea
      id: additional
      attributes:
          label: Additional Information
          description: Any additional information that may help us out.
          placeholder: |
              Ex: "I know that Paper has API <link here>"
      validations:
          required: false
